language: php
php:
  - 5.5
  - 5.6
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.secrethash vcs https://github.com/secrethash/dropmenu.git
  - composer require secrethash/dropmenu dev-master
  - composer update
  # - cp ./vendor/secrethash/dropmenu/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/secrethash/dropmenu/tests/config/app.php ./config
  # - php artisan vendor:publish
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - composer dump-autoload
  - php artisan dropmenu:migration
  - php artisan migrate
  - cd ./vendor/secrethash/dropmenu
  
script: "phpunit"