language: php
php:
  - 5.5
  - 5.6
before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.compasspointmedia vcs https://github.com/compasspointmedia/julietmenu.git
  - composer require compasspointmedia/julietmenu dev-master
  - composer update
  - composer install --no-interaction
  - php artisan key:generate
  # - cp ./vendor/compasspointmedia/julietmenu/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/compasspointmedia/julietmenu/tests/config/app.php ./config
  # - php artisan vendor:publish
  - composer dump-autoload
  - php artisan julietmenu:migration
  - php artisan migrate
  - cd ./vendor/compasspointmedia/julietmenu
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
script: "phpunit"
services:
  - mysql
cache:
  directories:
    - node_modules
    - vendor